version: 2.1

jobs:

  ruby-linters:
#    name: Test
#    context: global
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Check SECRET
          command: echo $SECRET
      - run:
          name: Check AWS_REGION
          command: echo $AWS_REGION
