version: 2
jobs:
  lint-charts:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v3.3.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add origin https://github.com/matic-insurance/ops-helm-charts
            git fetch origin master
            ct lint --config test/ct.yaml
workflows:
  version: 2
  lint:
    jobs:
      - lint-charts