{{ if (and .Values.webserver.enabled .Values.ingress.enabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "rails.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.type | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
  labels:
    app: {{ include "rails.name" . }}-ingres
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" . }}
    environment: {{ include "rails.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "rails.chart" . }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ include "rails.name" . }}
              servicePort: {{ .Values.webserver.port }}

{{- end }}