{{ if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rails.name" . }}-migrations
  labels:
    app: {{ include "rails.name" . }}-migrations
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" . }}
    environment: {{ include "rails.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "rails.chart" . }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "rails.name" . }}-migrations
        app.kubernetes.io/name: {{ include "rails.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ include "rails.version" . }}
        environment: {{ include "rails.environment" . }}
        product: {{ .Values.product }}
        helm.sh/chart: {{ include "rails.chart" . }}
    spec:
      containers:
      {{- $rails_name := include "rails.name" . -}}
      {{- range $index, $command := .Values.migrations.command }}
      - name: {{ $rails_name }}-migrations-{{ $index }}
        image: {{ $.Values.image.repository }}
        command: ["sh","-c","{{ $command }}"]
        {{ if $.Values.custom_configs.enabled -}}
        envFrom:
        - secretRef:
           name: {{ $.Values.product }}-envvars
        volumeMounts:
          {{- range $index, $config := $.Values.custom_configs.files}}
          - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" }}-vol
            mountPath: {{ $config }}
            subPath: {{ base $config }}
            readOnly: true
          {{- end }}
        {{- end -}}
      restartPolicy: Never
      {{- if $.Values.image_private_registry.enabled }}
      imagePullSecrets:
       - name: {{ $.Values.image_private_registry.secret }}
      {{- end }}
      {{ if $.Values.custom_configs.enabled -}}
      volumes:
        {{- range $index, $config := $.Values.custom_configs.files}}
        - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" }}-vol
          secret:           
            secretName: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" }}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end }}